export type Information = typeof infoConfig;

export const infoConfig = {
  name: "John-Arkerson",
  description: "Information that will go into components.",
  aboutInfo: {
    About: {
      desc: `I am a Software Developer based in the Northeast. Utilizing my experience with React, I have developed this website the utilizing the Next.js framework to showcase me professional experience, volunteer work, and personal hobbies.`,
    },
    Volunteer: {
      year: "Dec. 2019 - Jan. 2020",
      desc: `In December of 2019 a few cousins and I decided it would be a great opportunity to help our people after Hurricane Maria hit Puerto Rico. 
            We chose an amazing company called All Hands and Hearts. They gather volunteers from all over the world to help those in need. 
            Hurricane Maira devastated the island for years, leaving many without power, water or proper shelter. 
            Many homes received water damage both inside and out resulting in leaking roofs, crumbling walls and black mold throughout the premises. 
            The main tasks that we handled included removing and replacing the roofing sealant, disinfect the premises of black mold and repair walls and floors.`,
    },
    Education: {
      year: "2017 - 2021",
      desc: `In 2017, I entered Rowan University eager to learn all I could about programming. 
            To me, programming is like a jigsaw puzzle: you start with an overall picture of what you want, 
            then you dive in and peace together all the different parts that you need to ultimately create that final picture that you had envisioned. 
            In 2021, I graduated with honors (Magna Cum Laude) with a degree in Computer and Informatics with a concentration in Cyber Security and a concentration in Management of Information Security.`,
    },
  },
  widgetInfo: [
    {
      id: "c1",
      key: "1",
      label: "Python",
      year: "3 years",
      data: ` During my development career, I have created a multitude of applications for use on the factory floor. The most significant being the development of real-time data applications. These applications were .exe files that were installed on each of the tools on the factory floor as well as on dispatch screens mounted on the walls for operator use. The applications that were installed on the factory tools would take metric data generated by that specific tool and generate a multitude of plots that the engineer could use to assess if the tool's performance was within the acceptable range for what was needed with the product. \n
              The application that was installed on the dispatch screens would also take metric data from the database. However, this data was an aggregate of all the tool's measurements. These measurements were then plotted into SPC (Statistical Process Control) charts and displayed on the screen so operators could know when they have hit their product quota as well as if the tools needed to be adjusted for better performance.\n
              Other projects that I have developed and maintained include particle density measurement applications for the factory cleanroom for upper management to assess if the air filtration systems were working properly and, if not, how much it would affect product manufacturing. Additionally, I developed a multitude of back-end programs that interacted with the React environments that I managed. This will be covered in the React portion of this page.`,
      image: "/python.svg",
      header_style: "card_header_one",
      button_style: "card_btn_one",
      duration: "500",
    },
    {
      id: "c3",
      key: "3",
      label: "React",
      year: "3 years",
      data: ` In my previous position as a software engineer for Coherent, I oversaw the developement and management of 3 different internal websites for the company that were used in each of their factories across the world. The first of these websites was a statistical datasheet generator that was sent to the customer upon shipment of the product. The application would allow the user to select what customer, product and shipment date the delivery was scheduled for. Once confirmed, the application would pull thousands of data points for each product in the shipment and calculate the needed measurements for said product and generate an Excel page that could then be reviewed by the quality team.\n
              The second of these websites that I developed was a label generation application for both internal and customer use. The labels in question were generated in a programming language called ZPL II (Zebra Printing Language). The customer labels were labels that were generated in either English or Chinese depending on the specified customer. The application would then take the product information and generate a label with both human readable product information as well as QR codes for easy scanning from the customer. The internal labels were generated by operators upon receiving a shipment into the warehouse. The user would take the shipment and scan a QR code on the box and it would generate a label that had the QR code, product quantity, product code and receiving date.\n
              Once the warehouse label was generated the staff would then use the third website that I developed to help keep track of the current products in the warehouse. This application would take the generated barcode which, once scanned, would populate the page with the product that was scanned and the quantity that was to be removed for use on the factory floor. Once confirmed by the user, the application would remove the needed products from the SAP system as well as the SQL database to ensure that the products that were in the warehouse were the correct quantities that were listed in both databases to ensure that there were no inconsistencies between the actual products in the factory and the count in the database.`,
      image: "/react.svg",
      header_style: "card_header_three",
      button_style: "card_btn_three",
      duration: "1000",
    },
    {
      id: "c2",
      key: "2",
      label: "SQL",
      year: "3 years",
      data: ` Throughout all the projects that I developed I had the opportunity to develop my knowledge of SQL. While database management was not my main responsibility as a developer, I had the opportunity to learn how a large company handles their data management and how to better work with their systems through the development of my projects. I was able to handle tasks ranging from simple user permissions to complex data backlogging and tool data upload. As you read previously, there were many projects that I worked on that handled many thousands of lines of data that were sent from a multitude of tools in the factories around the world.`,
      image: "/sql.svg",
      header_style: "card_header_two",
      button_style: "card_btn_two",
      duration: "1500",
    },
    {
      id: "c5",
      key: "5",
      label: "Azure",
      year: "3 years",
      data: ` While in my role as a software engineer, I had my first introduction to Azure. While I had no prior experience with the application, I quickly understood how useful such an application could be in the development lifecycle. Throughout my time with my previous team, I was able to collaborate closely and see how helpful it can be to use the embedded branching strategy that they had in place. Having the ability to peer review updates before they go live is invaluable.\n 
              Before I left my previous employer, I had the opportunity to assist in implementing a CI/CD pipeline for the projects that I managed. While I am still inexperienced in this methodology, I plan to use this project to advance my knowledge on this topic. After deploying this project, my next step will be to learn all that I can about CI/CD pipelines and implement them into this project to better streamline this website development.`,
      image: "/code.svg",
      header_style: "card_header_four",
      button_style: "card_btn_four",
      duration: "2000",
    },
  ],
  componentInfo: [
    {
      label: "Profile",
      href: "/profile",
    },
  ],
  links: {
    github: "https://github.com/John-Arkerson/Resume-Website",
    // discord: "https://discord.gg/9b6yyZKmH4",
  },
};
